name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: input
    id: jira
    attributes:
      label: Jira Epic/Story
      description: If this feature is already planned in Jira, link it here
      placeholder: GAILP-XXX
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: As a [role], I need [feature] so that [benefit]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Business Priority
      description: How important is this feature?
      options:
        - Critical - Blocking major use case
        - High - Important for user experience
        - Medium - Nice to have
        - Low - Future consideration
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: Your rough estimate of implementation complexity
      options:
        - Low - Few hours
        - Medium - Few days
        - High - 1-2 weeks
        - Expert - Multiple weeks
        - Unknown
    validations:
      required: false

  - type: checkboxes
    id: affected-areas
    attributes:
      label: Affected Areas
      description: Which parts of the system would this affect?
      options:
        - label: Frontend/UI
        - label: Backend/API
        - label: Database
        - label: Authentication
        - label: Documentation
        - label: Infrastructure

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Add mockups, wireframes, or examples from other applications
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know this feature is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: false

  - type: checkboxes
    id: impact
    attributes:
      label: User Impact
      description: Who would benefit from this feature?
      options:
        - label: Executive users
        - label: Content creators/editors
        - label: Developers
        - label: End users/readers
        - label: AI agents

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided clear use cases and benefits
          required: true
        - label: This aligns with project goals
          required: true
